services:

  rviz:
    image: husarion/rviz:noetic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.rviz:/root/.rviz/default.rviz
    environment: 
      - DISPLAY=${DISPLAY:?You need to define display env}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://10.15.20.2:11311}
      - ROS_IP=${ROS_IP:-10.15.20.3}
      - LIBGL_ALWAYS_SOFTWARE=1