# Quick Start
# $ xhost local:root
# $ docker compose -f compose.host.yaml up

services:
  astra:
    image: husarion/astra:melodic
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/bus/usb
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
    command: roslaunch --wait astra_camera astra.launch

  rplidar:
    image: husarion/rplidar:melodic
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/ttyUSB0
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
    command: roslaunch --wait rplidar_ros rplidar.launch

  ros-master:
    image: ros:noetic-ros-core
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_IP=${ROS_IP:-127.0.0.1}
    command: roscore

  rviz:
    image: husarion/rviz:noetic
    restart: unless-stopped
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz/default.rviz
    environment: 
      - DISPLAY=${DISPLAY:?You need to define display env}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      # - LIBGL_ALWAYS_SOFTWARE=1

  frame_transformer:
    image: husarion/rviz:noetic
    restart: unless-stopped
    network_mode: host
    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
    command: rosrun tf static_transform_publisher 0 0 0 0 0 0 laser camera_link 0